### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by nickmessing** [nickmessing/vue-tinybase#1]
This issue will be used to track progress on the planned stuff.

First step is "migrating" the "[ui-react](https://tinybase.org/api/ui-react/)" and "[ui-react-dom](https://tinybase.org/api/ui-react-dom/)" stuff.

- Add unit tests

  - [x] #2

- Migrate `ui-react`

  - [ ] Checkpoints hooks
    - [x] `useCheckpoint`
    - [x] `useCheckpointIds`
    - [ ] `useCheckpointIdsListener`
    - [ ] `useCheckpointListener`
    - [x] `useCheckpoints` - [`injectCheckpoints`](https://next.vue-tinybase.com/api/checkpoints/context.html#inject-checkpoints)
    - [x] ~`useCheckpointsIds`~ - Not needed. Different design.
    - [x] ~`useCheckpointsOrCheckpointsById`~ - Not needed. Different design.
    - [ ] `useCreateCheckpoints`
    - [x] ~`useGoBackwardCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] ~`useGoForwardCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] ~`useGoToCallback`~ - Not needed. Caching functions is not needed in vue.
    - [ ] `useRedoInformation`
    - [x] ~`useSetCheckpointCallback`~ - Not needed. Caching functions is not needed in vue.
    - [ ] `useUndoInformation`
  - [ ] Indexes hooks
  - [ ] Metrics hooks
  - [ ] Persister hooks
  - [ ] Queries hooks
  - [ ] Relationships hooks
  - [x] Store hooks
    - [x] ~`useCreateStore`~ - Not needed. Using store created outside of vue-tinybase.
    - [x] `useProvideStore` - [`provideStore`](https://vue-tinybase.com/api/store/context.html#provide-store)
    - [x] `useStore` - [`injectStore`](https://vue-tinybase.com/api/store/context.html#inject-store)
    - [x] ~`useStoreIds`~ - Not needed. Using stores created outside of vue-tinybase.
    - [x] ~`useStoreOrStoreById`~ - Not needed. Using stores created outside of vue-tinybase.
    - [x] ~`useDelTablesCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useHasTables`](https://vue-tinybase.com/api/store/composables.html#use-has-tables)
    - [x] `useHasTablesListener` - [`onHasTablesChange`](https://vue-tinybase.com/api/store/events.html#on-has-tables-change)
    - [x] ~`useSetTablesCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useTables`](https://vue-tinybase.com/api/store/composables.html#use-tables) (and writable [`tablesRef`](https://vue-tinybase.com/api/store/references.html#tables-ref))
    - [x] `useTablesListener` - [`onTablesChange`](https://vue-tinybase.com/api/store/events.html#on-tables-change)
    - [x] [`useTableIds`](https://vue-tinybase.com/api/store/composables.html#use-table-ids)
    - [x] `useTableIdsListener` - [`onTableIdsChange`](https://vue-tinybase.com/api/store/events.html#on-table-ids-change)
    - [x] ~`useDelTableCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useHasTable`](https://vue-tinybase.com/api/store/composables.html#use-has-table)
    - [x] [`useHasTableCell`](https://vue-tinybase.com/api/store/composables.html#use-has-table-cell)
    - [x] `useHasTableCellListener` - [`onHasTableCellChange`](https://vue-tinybase.com/api/store/events.html#on-has-table-cell-change)
    - [x] `useHasTableListener` - [`onHasTableChange`](https://vue-tinybase.com/api/store/events.html#on-has-table-change)
    - [x] ~`useSetTableCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useTable`](https://vue-tinybase.com/api/store/composables.html#use-table) (and writable [`tableRef`](https://vue-tinybase.com/api/store/references.html#table-ref))
    - [x] [`useTableCellIds`](https://vue-tinybase.com/api/store/composables.html#use-table-cell-ids)
    - [x] `useTableCellIdsListener` - [`onTableCellIdsChange`](https://vue-tinybase.com/api/store/events.html#on-table-cell-ids-change)
    - [x] `useTableListener` - [`onTableChange`](https://vue-tinybase.com/api/store/events.html#on-table-change)
    - [x] [`useRowIds`](https://vue-tinybase.com/api/store/composables.html#use-row-ids)
    - [x] `useRowIdsListener` - [`onRowIdsChange`](https://vue-tinybase.com/api/store/events.html#on-row-ids-change)
    - [x] [`useSortedRowIds`](https://vue-tinybase.com/api/store/composables.html#use-sorted-row-ids)
    - [x] `useSortedRowIdsListener` - [`onSortedRowIdsChange`](https://vue-tinybase.com/api/store/events.html#on-sorted-row-ids-change)
    - [x] ~`useAddRowCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] ~`useDelRowCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useHasRow`](https://vue-tinybase.com/api/store/composables.html#use-has-row)
    - [x] `useHasRowListener` - [`onHasRowChange`](https://vue-tinybase.com/api/store/events.html#on-has-row-change)
    - [x] [`useRow`](https://vue-tinybase.com/api/store/composables.html#use-row) (and writable [`rowRef`](https://vue-tinybase.com/api/store/references.html#row-ref)
    - [x] [`useRowCount`](https://vue-tinybase.com/api/store/composables.html#use-row-count)
    - [x] `useRowCountListener` - [`onRowCountChange`](https://vue-tinybase.com/api/store/events.html#on-row-count-change)
    - [x] `useRowListener` - [`onRowChange`](https://vue-tinybase.com/api/store/events.html#on-row-change)
    - [x] ~`useSetPartialRowCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] ~`useSetRowCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useCellIds`](https://vue-tinybase.com/api/store/composables.html#use-cell-ids)
    - [x] `useCellIdsListener` - [`onCellIdsChange`](https://vue-tinybase.com/api/store/events.html#on-cell-ids-change)
    - [x] [`useCell`](https://vue-tinybase.com/api/store/composables.html#use-cell) (and writable [`cellRef`](https://vue-tinybase.com/api/store/references.html#cell-ref))
    - [x] `useCellListener` - [`onCellChange`](https://vue-tinybase.com/api/store/events.html#on-cell-change)
    - [x] ~`useDelCellCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useHasCell`](https://vue-tinybase.com/api/store/composables.html#use-has-cell)
    - [x] `useHasCellListener` - [`onHasCellChange`](https://vue-tinybase.com/api/store/events.html#on-has-cell-change)
    - [x] ~`useSetCellCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] ~`useDelValuesCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useHasValues`](https://vue-tinybase.com/api/store/composables.html#use-has-values)
    - [x] `useHasValuesListener` - [`onHasValuesChange`](https://vue-tinybase.com/api/store/events.html#on-has-values-change)
    - [x] ~`useSetPartialValuesCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] ~`useSetValuesCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useValues`](https://vue-tinybase.com/api/store/composables.html#use-values) (and writable [`valuesRef`](https://vue-tinybase.com/api/store/references.html#values-ref))
    - [x] `useValuesListener` - [`onValuesChange`](https://vue-tinybase.com/api/store/events.html#on-values-change)
    - [x] ~`useDelValueCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useHasValue`](https://vue-tinybase.com/api/store/composables.html#use-has-value)
    - [x] `useHasValueListener` - [`onHasValueChange`](https://vue-tinybase.com/api/store/events.html#on-has-value-change)
    - [x] ~`useSetValueCallback`~ - Not needed. Caching functions is not needed in vue.
    - [x] [`useValue`](https://vue-tinybase.com/api/store/composables.html#use-value) (and writable [`valueRef`](https://vue-tinybase.com/api/store/references.html#value-ref))
    - [x] [`useValueIds`](https://vue-tinybase.com/api/store/composables.html#use-value-ids)
    - [x] `useValueIdsListener` - [`onValueIdsChange`](https://vue-tinybase.com/api/store/events.html#on-value-ids-change)
    - [x] `useValueListener` - [`onValueChange`](https://vue-tinybase.com/api/store/events.html#on-value-change)
    - [x] `useDidFinishTransactionListener` - [`onDidFinishTransaction`](https://vue-tinybase.com/api/store/events.html#on-did-finish-transaction)
    - [x] `useStartTransactionListener` - [`onStartTransaction`](https://vue-tinybase.com/api/store/events.html#on-start-transaction)
    - [x] `useWillFinishTransactionListener` - [`onWillFinishTransaction`](https://vue-tinybase.com/api/store/events.html#on-will-finish-transaction)
  - [ ] Checkpoints components
  - [ ] Context components
  - [ ] Indexes components
  - [ ] Metrics components
  - [ ] Queries components
  - [ ] Relationships components
  - [ ] Store components
  
- Migrate `ui-react-dom`

  - [ ] List things needed to be migrated

**Comment by nickmessing** [comment]
There's no work planned on this project, due to lack of community interest, and I'm not using it anywhere. 
If you have a project that needs this, ping me and I'll try to find time to rebuild/finish this
